name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20"]
    
    steps:
    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Export Env
      run: export GO111MODULE=on
    - name: Build
      run: go mod tidy
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./client/...
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash)